---
apiVersion: v1
kind: List

items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mongo-db
  spec:
    replicas: 1
    selector:
      matchLabels:
        tfg: mongo
    template:
      metadata:
        labels:
          tfg: mongo
      spec:
        containers:
          - name: mongo
            image: mongo:latest
          - ports:
            - name: mongo
              containerPort: 27017
- apiVersion: v1
  kind: service
  metadata:
    name: mongo-db-service
  spec:
    type: LoadBalancer
    selector:
      tfg: mongo
    ports:
      - name: "mongo"
        protocol: TCP
        port: 27017
        targetPort: mongo
