---
apiVersion: v1
kind: List

items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dron
  spec:
    replicas: 1
    selector:
      matchLabels:
        tfg: dron
    template:
      metadata:
        labels:
          tfg: dron
      spec:
        containers:
          - name: dron
            image: divios/air-anchor-api:1.1.2-SNAPSHOT
            command:
              - bash
            args:
              - -c 
              - |
                  echo "87079264a7f5c5999dddedffd83dbc6b1653a308288a89aac5805420a371f7f0" > priv-key && 
                  tail -f /dev/null

